services:
  statusscout-landing:
    build:
      args:
        VITE_BASE_URL: ${VITE_BASE_URL}
        VITE_API_URL: ${VITE_API_URL}
        VITE_APP_URL: ${VITE_APP_URL}
        VITE_ENABLE_ANALYTICS: ${VITE_ENABLE_ANALYTICS}
        VITE_TURNSTILE_SITE_KEY: ${VITE_TURNSTILE_SITE_KEY}
        VITE_GTM_ID: ${VITE_GTM_ID}
        VITE_COOKIEBOT_ID: ${VITE_COOKIEBOT_ID}
    container_name: statusscout-landing
    restart: always
    ports:
      - "3005:80"